### ISSUE TITLE
code: 200 , message: Odoo server error

### ISSUE THREAD

**Issue by kururu-abdo** [ERP-Ukraine/odoo-rpc-dart#18]
the method search_read    worked fine
but  when i try to use method create
it result in:
{"jsonrpc": "2.0", "id": null, "error": {"code": 200, "message": "Odoo Server Error"}}

**Comment by lem8r** [comment]
Hi!

Method `create` must be called with empty `kwargs` even if they are not used.

Like so

```dart
var partner_id = await client.callKw({
  'model': 'res.partner',
  'method': 'create',
  'args': [
    {
      'name': 'Stealthy Wood',
    },
  ],
  'kwargs': {},
});
```

There might be other issues like expired session or security rules. Check your Odoo logs for traceback.

**Comment by kururu-abdo** [comment]
thanks

i have already send with  empty **kwargs**     

i will check odoo logs
