### ISSUE TITLE
Request reset password

### ISSUE THREAD

**Issue by gjae** [ERP-Ukraine/odoo-rpc-dart#19]
Hello, how to make request to odoo server for reset password?

**Comment by lem8r** [comment]
Hi!

Same as calling any other method on a model.

If auth_signup module is installed something like this should work:

by user's id known from session

```dart
client.callKw({
    'model': 'res.users',
    'method': 'action_reset_password',
    'args': [user_id,],
    'kwargs': {},
});
```

or by user's login

```dart
client.callKw({
    'model': 'res.users',
    'method': 'reset_password',
    'args': ['login_name',],
    'kwargs': {},
});

**Comment by gjae** [comment]
> Hi!
> 
> Same as calling any other method on a model.
> 
> If auth_signup module is installed something like this should work:
> 
> by user's id known from session
> 
> ```dart
> client.callKw({
>     'model': 'res.users',
>     'method': 'action_reset_password',
>     'args': [user_id,],
>     'kwargs': {},
> });
> ```
> 
> or by user's login
> 
> ```dart
> client.callKw({
>     'model': 'res.users',
>     'method': 'reset_password',
>     'args': ['login_name',],
>     'kwargs': {},
> });
> ```

Ooh i thought'nt that i can call model methods. I thought that just called to models actions (like search or write), very thankyou!
