### ISSUE TITLE
update data in an existing module

### ISSUE THREAD

**Issue by aslamibnabdulla** [ERP-Ukraine/odoo-rpc-dart#20]
Hi,
How can we update data in a module .I want to change the name of driver  assigned to car in the fleet module.
Secondly, Can we stream into the Discuss module from apps ?
Can u show an example for both problems.

**Comment by lem8r** [comment]
https://github.com/ERP-Ukraine/odoo-rpc-dart/blob/master/example/odoo_rpc_example.dart#L79-L89

Just change model name and method.
