### ISSUE TITLE
code：100问题

### ISSUE THREAD

**Issue by 443933773** [ERP-Ukraine/odoo-rpc-dart#21]
![image](https://user-images.githubusercontent.com/50561990/132664523-7703852a-86ec-4102-a5cb-36782b04f26d.png)

**Comment by 443933773** [comment]
任意一个callKw请求都会报这个错
![image](https://user-images.githubusercontent.com/50561990/132664706-2fabff41-e9e4-4900-a83c-25c9c4e9757a.png)

**Comment by lem8r** [comment]
Hi!

What was the result of authentication call before that?

**Comment by 443933773** [comment]
Hi！身份调用正常
![image](https://user-images.githubusercontent.com/50561990/132666019-ebbd120f-faea-4cca-95a9-a31dc90e33b6.png)

**Comment by lem8r** [comment]
Well, maybe session was not extracted from cookies.
You need to debug [_updateSessionIdFromCookies](https://github.com/ERP-Ukraine/odoo-rpc-dart/blob/master/lib/src/odoo_client.dart#L140) to see if session value was stored.

If session was extracted - it is valid for next call.

**Comment by lem8r** [comment]
> Hi！身份调用正常
> ![image](https://user-images.githubusercontent.com/50561990/132666019-ebbd120f-faea-4cca-95a9-a31dc90e33b6.png)

In your case session id missing. It should look like following 
![image](https://user-images.githubusercontent.com/5942291/132687739-2f68c342-6926-4d3b-ab5d-ec9140dc3ec4.png)

In order to find the reason I need to check http headers that were sent to your client.

**Comment by 443933773** [comment]
hello ！

This is my request header 

![image](https://user-images.githubusercontent.com/50561990/132780732-0c06f906-0fa6-4c96-9297-c05c0fc0084d.png)

**Comment by 443933773** [comment]
hi！这个问题是因为odoo的安全验证导致的，在调试过程中我发现了这个一个问题，这是否是导致cookie消失的原因呢
![image](https://user-images.githubusercontent.com/50561990/132811975-d0b6d4d1-a609-4044-8f22-a33c2f8234d1.png)

**Comment by lem8r** [comment]
Maybe you're using flutter for web? It won't work at least because of https://github.com/odoo/odoo/pull/37853
