### ISSUE TITLE
您好 如何进行关联查询呢

### ISSUE THREAD

**Issue by 443933773** [ERP-Ukraine/odoo-rpc-dart#23]

**Comment by lem8r** [comment]
Hi,

Could you please provide more details?

**Comment by lem8r** [comment]
Do you mean how to read related fields?
The same way as Odoo's web client does it. Open network calls and you will see it.

For example, I opened sales order.
At first web client read fields on sale.order model
![image](https://user-images.githubusercontent.com/5942291/133821043-8b276a40-f5f9-416c-adbe-30a15cc748a4.png)

The response has tuples `(id, name)` for Many2one fields, so you can show it on interface without fetching extra data. And you have `id` to get more details if needed.
![image](https://user-images.githubusercontent.com/5942291/133821349-e32dfd3f-09ae-49cf-b031-e48c71533f7e.png)

And for One2many fields (order lines) it gives you ids which has to be fetched with second call.
![image](https://user-images.githubusercontent.com/5942291/133821487-34678b3b-2f4d-44c7-863f-2df116702a63.png)

Odoo client does exactly that: it fetches order lines with second call
![image](https://user-images.githubusercontent.com/5942291/133821596-139d398c-2c17-41c9-a911-8f245dc87f83.png)

And response is
![image](https://user-images.githubusercontent.com/5942291/133821682-f28eaea1-f178-4541-8063-5e995be5d503.png)
