### ISSUE TITLE
May someone have a issue about picture showing in Flutter interface ?

### ISSUE THREAD

**Issue by excellencemichel** [ERP-Ukraine/odoo-rpc-dart#24]
When I fetch the patners data from and perform imageUrl in PartnerRepo but the images are not showing in the interface. I don't why beacause when I log the partners data I check image link is valid and I can show in browser tab. What can cause that ?

**Comment by lem8r** [comment]
Definitely not a RPC library issue.
This library is pure dart code and there is no link with flutter.

What is image url you're trying to show?

**Comment by excellencemichel** [comment]
Please, it is for underline Odoo Repsitory  https://github.com/ERP-Ukraine/odoo-repository-dart.git
There are images like partners or contacts avatar image, here is an example: http://94.23.13.202:14022/web/image?model=res.partner&id=26&field=image_128&unique=19112021185128

**Comment by lem8r** [comment]
The link is correct by itself. Maybe flutter widget has some limitations. You need to debug it.

**Comment by excellencemichel** [comment]
Okay thank you very much for all. I'll try again.
Odoo method `hasRight` can be called with this library ?

**Comment by lem8r** [comment]
There is no limitations of a library. You can call any rpc method that is public: not starts with underscore. See https://github.com/odoo/odoo/blob/0cf2ade4e6e959170906b4b0143e07909980b1d7/odoo/models.py#L116

**Comment by excellencemichel** [comment]
Okay. Thank you once again for everything !
