### ISSUE TITLE
Keep sessions when Apps closed

### ISSUE THREAD

**Issue by codexreloaded** [ERP-Ukraine/odoo-rpc-dart#27]
How to handle sessions when apps being closed and then apps re opening,

Because when apps is closed then opening again, it says Session Expired

Thanks

**Comment by lem8r** [comment]
Session changes on every request. There is session stream that sends new session value. You need to listen to that stream and store latest session value so when app starts next time you can pass restored session value to `OdooClient` instance.
See https://github.com/ERP-Ukraine/odoo-rpc-dart/blob/master/example/odoo_rpc_example.dart#L5
