### ISSUE TITLE
cannot get image from url

### ISSUE THREAD

**Issue by kururu-abdo** [ERP-Ukraine/odoo-rpc-dart#28]
i try to get image from the url  like you did in the example 
but i get this:

HTTP request failed, statusCode: 403,
 http://142.93.55.190:8069/web/image?model=property.base&field=pt_image&id=169&unique=20220217081743

**Comment by lem8r** [comment]
Hi,

It must be public image.
Non-public images require session in cookie which is not possible with flutter or other external client.
