### ISSUE TITLE
New Odoo Change data type in Saas DB

### ISSUE THREAD

**Issue by capricornius** [ERP-Ukraine/odoo-rpc-dart#29]
New Update in Odoo Saas db field serverVersion return a String.
Is required change file odoo_session.dart
> final int serverVersion => final String severVersion
>serverVersion: versionInfo[0] as int => serverVersion: versionInfo[0] as String
>serverVersion: newSessionId == '' ? 0 : serverVersion => serverVersion: newSessionId == '' ? '' : serverVersion,

I tested and work OK.

**Comment by lem8r** [comment]
Hi,

Thanks for reporting.

Indeed, for Odoo Online server version contains strings. https://github.com/odoo/odoo/blob/saas-15.3/odoo/release.py#L15

Need to change field types on our side.
