### ISSUE TITLE
connection with https

### ISSUE THREAD

**Issue by function2000** [ERP-Ukraine/odoo-rpc-dart#3]
When I use https, and error occurs as below
![image](https://user-images.githubusercontent.com/4005363/98183011-30aed980-1f42-11eb-92a3-e52243111cf5.png)

**Comment by function2000** [comment]
by the way, I update it like this,  maybe you can think about to change it in your code:

    return OdooSession(
      id: info['id'] as String,
      userId: info['uid'] as int,
      partnerId: info['partner_id'] as int,
      companyId: info['company_id'] as int,
      userLogin: info['username'] as String,
      userName: info['name'] as String,
      userLang: ctx['lang'] as String,
      userTz: ctx['tz'] ? 'true':'false',
      isSystem: info['is_system'] as bool,
      dbName: info['db'] as String,
      serverVersion: versionInfo[0] as int,
    );

**Comment by lem8r** [comment]
> When I use https, and error occurs as below
> ![image](https://user-images.githubusercontent.com/4005363/98183011-30aed980-1f42-11eb-92a3-e52243111cf5.png)
> 

Which version of odoo are you running?

**Comment by function2000** [comment]
it is version 13.
