### ISSUE TITLE
[Request] Anyone tried using this plugin with Open ERP ?

### ISSUE THREAD

**Issue by mdev88** [ERP-Ukraine/odoo-rpc-dart#33]
I have a client that uses Open ERP 6, and I was wondering if this package will work with that.

Thanks

**Comment by lem8r** [comment]
I have no Idea. Lowest tested version is 9.

**Comment by mdev88** [comment]
This package is not compatible with OpenERP. I managed to geet it working using another package called `xml_rpc`.
