### ISSUE TITLE
message: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by soufiane0123** [ERP-Ukraine/odoo-rpc-dart#34]
I follow the documentation in the [pub.dev](https://pub.dev/packages/odoo_rpc) but i get this error :

![image](https://user-images.githubusercontent.com/111284741/195072463-f70caa8d-a3bb-4d94-8d96-5e5854bff703.png)

**code :**
![image](https://user-images.githubusercontent.com/111284741/195070953-c2c614cf-ea2a-417b-bf2f-dcd992583e54.png)

**Comment by lem8r** [comment]
Hi,

Maybe you can show full traceback where is stated which url gives 404?

**Comment by soufiane0123** [comment]
I tested in postman is work fine 
![image](https://user-images.githubusercontent.com/111284741/195077632-ce5e2f96-5a4f-4ebc-9464-7ba765c97dda.png)

**Comment by lem8r** [comment]
This not a traceback.

**Comment by soufiane0123** [comment]
![image](https://user-images.githubusercontent.com/111284741/195078892-e417bff0-21fc-4b93-93b9-a568b64561de.png)

**Comment by soufiane0123** [comment]
I think the package work only https not http

**Comment by lem8r** [comment]
Same as odoo app. You have to provide correct proto. It wont follow redirects.
