### ISSUE TITLE
Extract a flutter application using Odoo_rpc package 

### ISSUE THREAD

**Issue by abdallahi34** [ERP-Ukraine/odoo-rpc-dart#44]
After i extract an application using this package , i can't sign in in the application that doesn't using debug mood , it's only work in debug mood .
When i use it in a debug mood , i get this error :
ClientException with SocketException : Failed host lookup :' my Url' ( OS Error: No address associated with hostname , error =7),

Please give me some clues to the solution

**Comment by lem8r** [comment]
> No address associated with hostname

Hi!
Which url address are you using to connect to Odoo instance? Looks like it has wrong hostname.

**Comment by abdallahi34** [comment]
Hi,
it wasn't , because it work perfectly in debug mood , but not in the extract app 
the url : https://cnsa-main-10458567.dev.odoo.com
do you have a clue
