### ISSUE TITLE
orpc.authenticate raise a null pointer exception

### ISSUE THREAD

**Issue by nafarrin** [ERP-Ukraine/odoo-rpc-dart#48]
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   main (package:odoo_rpc_flutter_demo/main.dart:54:12)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 💡 Logging with credentials
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'int' in type cast
#0      OdooSession.fromSessionInfo (package:odoo_rpc/src/odoo_session.dart:65:37)
#1      OdooClient.authenticate (package:odoo_rpc/src/odoo_client.dart:261:32)
<asynchronous suspension>
#2      main (package:odoo_rpc_flutter_demo/main.dart:55:5)
<asynchronous suspension>

**Comment by isyedaliraza** [comment]
Odoo 17 might changed something. Try to connect with Odoo 16 server.

**Comment by nafarrin** [comment]
thanks for the answer, unfortunately that's not an option in odoo cloud

**Comment by isyedaliraza** [comment]
I came across the same issue. I looked at the code and found there is some problem with parsing OdooSession. In Odoo 17,  the /web/session/authenticate response doesn't contain the company_id key.

**Comment by lem8r** [comment]
Thanks for reporting!
Please upgrade to v0.5.4
