### ISSUE TITLE
[Feature] Get list of available databases

### ISSUE THREAD

**Issue by mdev88** [ERP-Ukraine/odoo-rpc-dart#5]
Hello,

I was wondering if there was a way to get the list of available databases on a server using the current version of the package or if it's something that might be useful to implement as a new feature.

Thanks!

**Comment by mdev88** [comment]
I'll answer my own question:

`client.callRPC('/web/database/list', 'list', {});`

Done!

**Comment by lem8r** [comment]
It is worth mentioning that it is [recommeded](https://www.odoo.com/documentation/master/setup/deploy.html#database-manager-security) to close DB list on production databases, so you need to ask a user for DB name if `/web/database/list` route is closed.
