### ISSUE TITLE
Dependency Conflict: Incompatibility between odoo_rpc and flutter_lints 4.0.0

### ISSUE THREAD

**Issue by pradhanashwin** [ERP-Ukraine/odoo-rpc-dart#60]
Problem:
I am encountering a dependency conflict between the odoo_rpc package and the flutter_lints package in my Flutter project. When trying to use the latest version of odoo_rpc (version 0.5.4) along with flutter_lints version 4.0.0, the dependency resolution fails. The issue seems to arise because odoo_rpc depends on lints ^3.0.0, while flutter_lints version 4.0.0 depends on lints ^4.0.0.

**Comment by ernestoale97** [comment]
same issue
