### ISSUE TITLE
Cannot access avatar from the url

### ISSUE THREAD

**Issue by function2000** [ERP-Ukraine/odoo-rpc-dart#8]
From the example, we can get the URL of the avatar, but always get default image, as we did not login, so cannot get the real image of user.  How to resolve it?

**Comment by lem8r** [comment]
Hi!

You are acting as public user when not logged in. Public user [has limited access](https://github.com/odoo/odoo/blob/d8f7d7369f060f444bcebc0118cc5a2a650f6361/odoo/addons/base/security/base_security.xml#L26) to own `res_partner` only. Avatars are actually stored on relater partner.

This is Odoo's security limitation not rpc library issue.

**Comment by kururu-abdo** [comment]
so i can open image when session on?
@lem8r

**Comment by kururu-abdo** [comment]
HTTP request failed, statusCode: 403, http://142.93.55.190:8069/web/image?model=property.base&field=pt_image&id=169&unique=20220217081743
